kensetsubukka_server/accounts/urls.py
from django.contrib.auth.views import logout_then_login
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # Login
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', logout_then_login, name='logout'),
    # Signup
    path('signup/', views.Signup.as_view(), name='signup'),
    path('signup/done', views.SignupActivationConfirm.as_view(), name='signup_activation_confirm'),
    path('signup/complete/<token>', views.SignupActivationComplete.as_view(), name='signup_activation_complete'),
    # Password Reset
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    # Profile
    path('profile/', views.profile, name="profile")
]

kensetsubukka_server/kensetsubukka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.i18n import JavaScriptCatalog
from dashboard import views
urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    # # url(r'^', include('dashboard.urls[0]')),
]
urlpatterns += [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

kensetsubukka_server/accounts/models.py
from django.db import models

# Create your models here.

kensetsubukka_server/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.utils.translation import gettext_lazy
from django.contrib.auth import get_user_model
from dashboard.models import User_dashboard
from django.core.exceptions import ObjectDoesNotExist
from django.forms import ValidationError
User = get_user_model()
allowed_domain = ["@****","@****","@****"]


#Login
class LoginForm(AuthenticationForm):
    def clean_username(self):
        username = self.data['username']
        try:
            username = User.objects.get(email=username).username
        except ObjectDoesNotExist:
            raise ValidationError(gettext_lazy("Please enter the correct Email address."))
        return username

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label=gettext_lazy('Email')
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

# Signup
class SignupForm(UserCreationForm):
    last_name = forms.CharField(label=gettext_lazy("Last Name"))
    first_name = forms.CharField(label=gettext_lazy("First Name"))
    username = forms.CharField(label=gettext_lazy("Username"))
    email = forms.EmailField(label="Email")

    def clean_email(self):
        data = self.cleaned_data['email']
        count = 0
        for domain in allowed_domain:
            if domain not in data:   # any check you need
                count+=1
        if count==len(allowed_domain):
            raise forms.ValidationError(gettext_lazy("Incorrect email address"))
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError(gettext_lazy("Email already exists"))
        return data

    class Meta:
        model = User
        fields = ('email', 'last_name', 'first_name', 'username')
        unique = ['username','email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('username')
        for field in self.fields.values():
            # print(field)
            field.widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        user = super().save(False)
        current_domain = ""
        for domain in allowed_domain:
            if domain in user.email:
                current_domain = domain
                break
        user.username = user.email[:-(len(current_domain))]
        user = super().save()

        return user

# PasswordReset
class PasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class PasswordResetConfirmForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class ProfileForm(forms.ModelForm):
    last_name = forms.CharField(label=gettext_lazy("Last Name"))
    first_name = forms.CharField(label=gettext_lazy("First Name"))
    username = forms.CharField(label=gettext_lazy("Username"))
    email = forms.EmailField(label=gettext_lazy("Email"))

    def clean_email(self):
        data = self.cleaned_data['email']
        count = 0
        for domain in allowed_domain:
            if domain not in data:   # any check you need
                count+=1
        if count==len(allowed_domain):
            raise forms.ValidationError(gettext_lazy("Incorrect email address"))
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError(gettext_lazy("Email already exists"))
        return data

    class Meta:
        model = User
        fields = {'last_name','first_name','username','email'}
        unique = ['username','email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['readonly']=True
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

kensetsubukka_server/accounts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import Http404, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.views import generic
from django.urls import reverse_lazy
from .forms import LoginForm, SignupForm, PasswordResetForm, PasswordResetConfirmForm, ProfileForm
from django.shortcuts import render
from django.core.mail import send_mail
# Create your views here.
from dashboard.models import User_dashboard,Request
User = get_user_model()

def create_demo_request(dashboard):
    req = Request.objects.create(connected_dashboard=dashboard)
    print(req)
    return req

def create_user_dashboard(user):
    if User_dashboard.objects.filter(connected_user=user).exists():
        dashboard = User_dashboard.objects.get(connected_user=user)
    else:
        dashboard = User_dashboard.objects.create(connected_user=user)
    # create_demo_request(dashboard)
    return dashboard

#Login

class Login(LoginView):
    form_class = LoginForm
    template_name = 'pages/login.html'


#Signup
class Signup(generic.CreateView):
    template_name = 'pages/signup.html'
    form_class = SignupForm
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
            'settings': settings,
        }
        subject = render_to_string('email/account_activation_confirm_subject.txt', context).strip()
        message = render_to_string('email/account_activation_confirm_message.txt', context)
        print(subject)
        print(message)
        user.email_user(subject,message)
        return redirect('accounts:signup_activation_confirm')

class SignupActivationConfirm(generic.TemplateView):
    template_name = 'pages/signup_activation_confirm.html'

class SignupActivationComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_anme = 'pages/signup_activation_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24*10000) # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        print(token)
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)
            user = User.objects.get(pk=user_pk)
            print(user, user.is_active)
            user.is_active=True
            create_user_dashboard(user)
            user.save()
            return redirect('dashboard:index')
    
        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    create_user_dashboard(user)
                    return redirect('dashboard:index')
        return HttpResponseBadRequest()


# Password Reset
class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    form_class = PasswordResetForm
    subject_template_name = 'email/password_reset_subject.txt'
    email_template_name = 'email/password_reset_message.txt'
    template_name = 'pages/password_reset.html'
    # user.email_user(subject,message)
    success_url = reverse_lazy('accounts:password_reset_done')
    extra_email_context = {
        'settings' : settings,
    }

class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'pages/password_reset_done.html'

class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = PasswordResetConfirmForm
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'pages/password_reset_confirm.html'

class PasswordResetComplete(PasswordResetCompleteView):
    template_name = 'pages/password_reset_complete.html'


# What use of this ???? 
# Where is pages-user-profile.html ????
@login_required
def profile(request):
    if request.method == "POST":
        profile_form = ProfileForm(request.POST, instance=request.user)
        if profile_form.is_valid():
            profile_form.save()
            return HttpResponseRedirect("/accounts/profile")
    else:
        profile_form = ProfileForm(instance=request.user)

    return render(request, "pages/pages-user-profile.html", context={"form": profile_form})




        

kensetsubukka_server/accounts/templates/pages/login.html
{% extends "base-accounts.html" %}
{% load static %}
{% load i18n %}
{% block body_accounts %}
<form action="" method="POST">
    {% csrf_token %}
    {% include "common/accounts-form.html" %}
    <div class="form-group mb-lg">
        <a href="{% url "accounts:password_reset" %}" class="pull-right">{% trans "Lost Password?" %}</a>
    </div>
    {% trans "Remember Me" as login_text %}
    {% trans "Login" as btn_text %}
    {% include "common/accounts-checkbox.html" with label_text=login_text button=btn_text %}
    <!-- {% include "common/accounts-sns.html" %} -->
    {% trans "Signup" as link_text %}
    {% trans "Don't have an account yet?" as nopass_text %}
    {% include "common/accounts-p.html" with name=link_text href="../signup" text=nopass_text %}
</form>
{% endblock %}

kensetsubukka_server/accounts/templates/pages/password_reset.html
{% extends "base-accounts.html" %}
{% load static %}
{% load i18n %}
{% block body_accounts %}
<form action="" method="POST">
    {% csrf_token %}
    {% trans "Send" as btn_text %}
    {% include "common/accounts-content.html" with title="パスワードリセット" text="パスワードをリセットするメールアドレスを下記の入力欄に入力して下さい。" %}
    {% include "common/accounts-form.html" %}
    {% include "common/accounts-button.html" with name=btn_text %}
    <!-- {% include "common/accounts-p.html" with name="Login" href="../login" text=rem %} -->
</form>
{% endblock %}

kensetsubukka_server/accounts/templates/pages/password_reset_complete.html
{% extends "base-accounts.html" %}
{% load static %}

{% block body_accounts %}
<form action="{% url "accounts:login" %}" method="POST">
    {% csrf_token %}
    {% include "common/accounts-content.html" with title="パスワードリセット完了" text="パスワード再設定を完了しました。下記から、再度ログインして下さい。" %}
    {% include "common/accounts-button.html" with name="Login" %}
</form>
{% endblock %}

kensetsubukka_server/accounts/templates/pages/password_reset_confirm.html
{% extends "base-accounts.html" %}
{% load static %}

{% block body_accounts %}
<form action="" method="POST">
    {% csrf_token %}
    {% include "common/accounts-content.html" with title="パスワードリセット" text="現在のパスワードをリセットします。新しいパスワードを入力して下さい。" %}
    {% include "common/accounts-form.html" %}
    {% include "common/accounts-button.html" with name="Reset" %}
</form>
{% endblock %}

kensetsubukka_server/accounts/templates/pages/password_reset_done.html
{% extends "base-accounts.html" %}
{% load static %}

{% block body_accounts %}
<form action="" method="POST">
    {% csrf_token %}
    {% include "common/accounts-content.html" with title="パスワードリセット（メール送信）" text="指定されたメールアドレスへ確認メールを送信しましたので、メールに記載されているリンクからパスワードの再設定を行ってください。" %}
    {% include "common/accounts-p.html" with name="Login" href="../login" text="Remembered?" %}
</form>
{% endblock %}

kensetsubukka_server/accounts/templates/pages/signup.html
{% extends "base-accounts.html" %}
{% load static %}
{% load i18n %}
{% block body_accounts %}
<form action="" method="POST">
    {% csrf_token %}
    {% trans "label_text" as Label_Text %}
	{% trans "Signup" as btn_text %}
	{% trans "Already have an account?" as nopass_text %}
    {% include "common/accounts-form.html" %}
    {% include "common/accounts-checkbox.html" with label_name=terms label_text=Label_Text button=btn_text %}
    <!-- {% include "common/accounts-sns.html" %} -->
    {% trans "Login" as link_text %}
    {% include "common/accounts-p.html" with name=link_text href="../login" text=nopass_text %}
</form>
{% endblock %}

kensetsubukka_server/accounts/templates/pages/signup_activation_complete.html
{% extends "base-accounts.html" %}
{% load static %}

{% block body_accounts %}
<form action="{% url "accounts:login" %}" method="POST">
    {% csrf_token %}
    {% include "common/accounts-content.html" with title="本登録完了のお知らせ" text="本登録が完了しました。登録されたメールアドレスとパスワードでログインしてください。" %}
    {% include "common/accounts-button.html" with name="Login" %}
</form>
{% endblock %}

kensetsubukka_server/accounts/templates/pages/signup_activation_confirm.html
{% extends "base-accounts.html" %}
{% load static %}

{% block body_accounts %}
<form action="" method="POST">
    {% csrf_token %}
    {% include "common/accounts-content.html" with title="仮登録完了のお知らせ" text="会員登録確認メールを送信しました。まだ、会員登録は完了していません。確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。" %}
    {% include "common/accounts-p.html" with name="メールが届かない場合" href="../signup" %}
</form>
{% endblock %}