scraping-estimation-tool/scraping_estimation_tool/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tool.urls')),
    # path('tool/', include('tool.urls')),
    # url(r'^tool/', include('tool.urls')),
]

scraping-estimation-tool/tool/urls.py
from django.urls import include, path, re_path

from . import views

app_name = 'tool'

urlpatterns = [
    path('home/', views.index, name='index'),
    path('input/', views.input, name='input'),
    path('entry/', views.entry, name='entry'),
    path('domain/', views.domain, name='domain'),
    path('webscan/<domain>/', views.webscan, name='webscan'),
    # path('webscan/', views.webscan, name='webscan'),
    path('view_web/', views.view_web, name='view_web'),
]



# from django.urls import include, path, re_path
# from . import views
# from .subviews import youtube_views
# app_name = 'dashboard'

# urlpatterns = [
#     path('home/', views.index, name='index'),
#     path('twitter/home/', views.twitter_home, name='twitter_home'),
#     path('twitter/daily/', views.twitter_daily, name='twitter_daily'),
#     path('youtube/home/', youtube_views.home, name='youtube_home'),
#     path('youtube/daily/', youtube_views.daily, name='youtube_daily'),
#     path('email/', views.send_email_view, name='email'),
#     re_path(r'^.*\.html', views.generate_html, name='generate_html'),
# ]

scraping-estimation-tool/tool/models.py
from django.db import models

# Create your models here.

class DomainInfo(models.Model):
	
	domain = models.CharField(max_length=150, primary_key=True)

	first_byte_time = models.FloatField(null=True)
	complete_page_load_time = models.FloatField(null=True)
	https_score = models.FloatField(null=True)
	https_2_score = models.FloatField(null=True)
	page_status_score = models.FloatField(null=True)
	connection_time = models.FloatField(null=True)

	website_overall_score = models.PositiveIntegerField(default=0,null=True)
	in_page_links = models.TextField(null=True)
	ip =  models.TextField(null=True)
	doc_type =  models.TextField(null=True)
	encoding =  models.TextField(null=True)
	custom_error_page =  models.TextField(null=True)
	language =  models.TextField(null=True)
	url_parameters =  models.TextField(null=True)
	discovered_pages = models.TextField(null=True)
	traffic_estimation = models.TextField(null=True)
	traffic_rank = models.TextField(null=True)
	
	page_speed_score = models.FloatField(null=True)

	city = models.TextField(null=True)
	isp = models.TextField(null=True)
	country = models.TextField(null=True)
	internet_company = models.TextField(null=True)
	timezone = models.TextField(null=True)
	region_name = models.TextField(null=True) 

class DifficultyInfo(models.Model):

	domain = models.CharField(max_length=150, primary_key=True)

	total_js_files = models.PositiveIntegerField(default=0,null=True)
	js_difficulty = models.FloatField(default=0,null=True)
	total_forms = models.PositiveIntegerField(default=0,null=True)
	form_difficulty = models.FloatField(default=0,null=True)

scraping-estimation-tool/tool/forms.py
from django import forms


class JavascriptForm(forms.Form):
	domain = forms.CharField(label='Domain', max_length=200)
	url_label = forms.CharField(label='URL', max_length=1000)
	xpath_box = forms.CharField(label='xpath_list')

scraping-estimation-tool/tool/views.py
import json
import random
import time
import requests
from django.http import HttpResponse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from .forms import JavascriptForm
from .models import DomainInfo, DifficultyInfo
from .js_level import *
from .form_data_level import *
import mysql.connector

def save_to_db(domain, js_data_items , form_data_items):
	db = mysql.connector.connect(
			host="localhost",
			user="root",
			passwd="Helloworld@12345",
			database="set_database",
			use_unicode=True, 
			charset="utf8"
		)
		
	cursor = db.cursor()

	query = """INSERT INTO tool_difficultyinfo (domain, total_js_files, js_difficulty, total_forms, form_difficulty) 
				VALUES (%s, %s, %s, %s, %s) ON DUPLICATE KEY UPDATE total_js_files=%s, js_difficulty=%s,
				 total_forms=%s, form_difficulty=%s"""
	try:
		cursor.execute(query, tuple([domain,js_data_items['total_js_files'],js_data_items['js_difficulty'],
			form_data_items['total_forms'],form_data_items['form_difficulty'],js_data_items['total_js_files'],
			js_data_items['js_difficulty'],form_data_items['total_forms'],form_data_items['form_difficulty']]))
		db.commit()
		print("MySQL Success: Data inserted!!")
	except mysql.connector.Error as e:
		print("MySQL Error: ", e, query)
	cursor.close()
	db.close()


def index(request): 
	return render(request, 'index.html')

def entry(request):
	return render(request, 'entry.html')

def input(request): 
	if request.method == 'POST':
		form = JavascriptForm(request.POST)
		if form.is_valid():
			domain = form.cleaned_data['domain']
			url = form.cleaned_data['url_label']
			xpath_str = form.cleaned_data['xpath_box']
			xpath_list = xpath_str.split(',')
			print(xpath_list)
			form_data_items = form_data(url)
			js_data_items = js_data(url,xpath_list)

			print(form_data_items)
			print(js_data_items)
			save_to_db(domain, js_data_items, form_data_items)
			
			js_dict = {url: xpath_list}
			return HttpResponseRedirect('/input/')

	else:
		form = JavascriptForm()

	return render(request, 'input.html', {'form': form})

def domain(request):
	fields = ['domain']
	domains  = DomainInfo.objects.all().values(*fields)
	context = {'domain_list': domains}
	return render(request, 'domain.html', context)

def webscan(request, domain):
	domain_info  = DomainInfo.objects.filter(domain=domain).values()
	difficulty_info = DifficultyInfo.objects.filter(domain=domain).values()
	context = {'domain_info': domain_info[0],'difficulty_info':difficulty_info[0]}
	return render(request, 'webscan_page.html', context)

def view_web(request):
	if request.method == 'POST':
		
		link = request.POST.get("link")
		domain = request.POST.get("domain")

		db = mysql.connector.connect(
			host="localhost",
			user="root",
			passwd="Helloworld@12345",
			database="set_database",
			use_unicode=True, 
			charset="utf8"
		)
		
		cursor = db.cursor()

		query = """INSERT INTO tool_domaininfo (domain) VALUES (%s) ON DUPLICATE KEY UPDATE domain=%s"""
		try:
			cursor.execute(query, tuple([domain,domain]))
			db.commit()
			print("MySQL Success: Data inserted!!")
		except mysql.connector.Error as e:
			print("MySQL Error: ", e, query)

		query = """INSERT INTO tool_difficultyinfo (domain) VALUES (%s, %s, %s, %s, %s) ON DUPLICATE KEY UPDATE domain=%s"""
		try:
			cursor.execute(query, tuple([domain,domain]))
			db.commit()
			print("MySQL Success: Data inserted!!")
		except mysql.connector.Error as e:
			print("MySQL Error: ", e, query)
	
		cursor.close()
		db.close()

		data1 = {
		  'project': 'estimation_tool_scrapy',
		  'spider': 'speed_score',
		  'domain': domain
		}
		data2 = {
		  'project': 'estimation_tool_scrapy',
		  'spider': 'testmysite',
		  'domain': domain
		}
		data3 = {
		  'project': 'estimation_tool_scrapy',
		  'spider': 'woorank',
		  'domain': domain
		}
		

		response1 = requests.post('http://localhost:6800/schedule.json', data=data1)
		response2 = requests.post('http://localhost:6800/schedule.json', data=data2)
		response3 = requests.post('http://localhost:6800/schedule.json', data=data3)

		time.sleep(120)

		domain_info  = DomainInfo.objects.filter(domain=domain).values()

		ip=domain_info[0]['ip']

		data4 = {
		  'project': 'estimation_tool_scrapy',
		  'spider': 'ip',
		  'domain': domain,
		  'ip':ip
		}

		if ip is not None:
			response4 = requests.post('http://localhost:6800/schedule.json', data=data4)

		return HttpResponseRedirect('/entry/')
	else:
		return HttpResponse(status=200)

scraping-estimation-tool/tool/templates/base-accounts.html
{% extends "base.html" %}
{% load static %}

{% block body_content %}
<section class="body-sign">
    <div class="center-sign">
        <a href="/" class="logo pull-left">
            <img src="{% static 'images/logo.png' %}" height="54" alt="Porto Admin" />
        </a>
        <div class="panel panel-sign">
            <div class="panel-title-sign mt-xl text-right">
                <h2 class="title text-uppercase text-bold m-none"><i class="fa fa-user mr-xs"></i> Account</h2>
            </div>
            <div class="panel-body">
                {% block body_accounts %}{% endblock %}
            </div>
        </div>
        {% include "common/footer.html" %}
    </div>
</section>
{% endblock %}

scraping-estimation-tool/tool/templates/base.html
{% load static %}
<!doctype html>
<html class="{% block html_class %}fixed{% endblock %}">
<head>
    <!-- Basic -->
    <meta charset="UTF-8">
    <title>{{ PROJECT_NAME }}</title>
    <meta name="keywords" content="HTML5 Admin Template" />
    <meta name="description" content="JSOFT Admin - Responsive HTML5 Template">
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <!-- Web Fonts  -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" type="text/css">
    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.css' %}" />
    <link rel="stylesheet" href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-datepicker/css/datepicker3.css' %}" />
    <!-- <link rel="stylesheet" href="{% static 'custom/css/reset.css' %}" /> -->
    {% block css_common %}{% endblock %}
    <!-- Theme CSS -->
    <link rel="stylesheet" href="{% static 'css/theme.css' %}" />
    <!-- Skin CSS -->
    <link rel="stylesheet" href="{% static 'css/skins/default.css' %}" />
    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/theme-custom.css' %}">
    <!-- Head Libs -->
    <script src="{% static 'vendor/modernizr/modernizr.js' %}"></script>
</head>
<body>
{% block body_content %}
    <section class="body">
        {% include "common/header.html" %}
        <div class="inner-wrapper">
            {% include "common/sidebar.html" %}
            {% block content %}{% endblock %}
        </div>
        {% include "common/sidebar-right.html" %}
    </section>
{% endblock %}

<!-- Vendor -->
<script src="{% static 'vendor/jquery/jquery.js' %}"></script>
<script src="{% static 'vendor/jquery-browser-mobile/jquery.browser.mobile.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.js' %}"></script>
<script src="{% static 'vendor/nanoscroller/nanoscroller.js' %}"></script>
<script src="{% static 'vendor/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'vendor/magnific-popup/magnific-popup.js' %}"></script>
<script src="{% static 'vendor/jquery-placeholder/jquery.placeholder.js' %}"></script>

<!-- Custom -->
<script src="{% static 'custom/js/base.js' %}"></script>
<!-- Common js -->
{% block js_common %}{% endblock %}

<!-- Theme Base, Components and Settings -->
<script src="{% static 'js/theme.js' %}"></script>
<!-- Theme Custom -->
<script src="{% static 'js/theme.custom.js' %}"></script>
<!-- Theme Initialization Files -->
<script src="{% static 'js/theme.init.js' %}"></script>

<!-- Examples -->
{% block js %}{% endblock %}
</body>
</html>

scraping-estimation-tool/tool/templates/common/error.html
{% load static %}
<div class="row">
    <div class="col-md-8">
        <div class="main-error mb-xlg">
            <h2 class="error-code text-dark text-center text-semibold m-none">{{ title }} <i class="fa fa-file"></i></h2>
            <p class="error-explanation text-center">{{ message }}</p>
        </div>
    </div>
    <div class="col-md-4">
        <h4 class="text">Here are some useful links</h4>
        <ul class="nav nav-list primary">
            <li><a href="#"><i class="fa fa-caret-right text-dark"></i> Dashboard</a></li>
            <li><a href="#"><i class="fa fa-caret-right text-dark"></i> User Profile</a></li>
            <li><a href="#"><i class="fa fa-caret-right text-dark"></i> FAQ's</a></li>
        </ul>
    </div>
</div>

scraping-estimation-tool/tool/templates/common/footer.html
{% load static %}
<p class="text-center text-muted mt-md mb-md">
    &copy; 2019 All Rights Reserved. <a href="{{ COMPANY_URL }}" target="_blank">{{ COMPANY_NAME }}</a>.
</p>

scraping-estimation-tool/tool/templates/common/header-right.html
{% load static %}
<header class="page-header">
    <h2>{{ title }}</h2>
    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li><a href="{% url 'tool:index' %}"><i class="fa fa-home"></i></a></li>
            <li><span>{{ parent_dir }}</span></li>
            <li><span>{{ child_dir }}</span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

scraping-estimation-tool/tool/templates/common/header.html
{% load static %}
<header class="header">
    <div class="logo-container">
        <a href="../" class="logo"><img src="{% static 'images/logo.png' %}" height="35" alt="Logo" /></a>
        <div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
            <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>
    <!-- start: search & user box -->
    <div class="header-right">
        <form action="../pages/pages-search-results.html" class="search nav-form" style="margin-bottom: 0;">
            <div class="input-group input-search">
                <input type="text" class="form-control" name="q" id="q" placeholder="Search...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <span class="separator"></span>
        <ul class="notifications">
            <li>
                <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                    <i class="fa fa-tasks"></i>
                    <span class="badge">3</span>
                </a>
                <div class="dropdown-menu notification-menu large">
                    <div class="notification-title">
                        <span class="pull-right label label-default">3</span>Tasks
                    </div>
                    <div class="content">
                        <ul>
                            <li>
                                <p class="clearfix mb-xs">
                                <span class="message pull-left">Generating Sales Report</span>
                                <span class="message pull-right text-dark">60%</span>
                                </p>
                                <div class="progress progress-xs light">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
                                </div>
                            </li>
                            <li>
                                <p class="clearfix mb-xs">
                                <span class="message pull-left">Importing Contacts</span>
                                <span class="message pull-right text-dark">98%</span>
                                </p>
                                <div class="progress progress-xs light">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100" style="width: 98%;"></div>
                                </div>
                            </li>
                            <li>
                                <p class="clearfix mb-xs">
                                <span class="message pull-left">Uploading something big</span>
                                <span class="message pull-right text-dark">33%</span>
                                </p>
                                <div class="progress progress-xs light mb-xs">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%;"></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
            <li>
                <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                    <i class="fa fa-envelope"></i>
                    <span class="badge">4</span>
                </a>
                <div class="dropdown-menu notification-menu">
                    <div class="notification-title">
                        <span class="pull-right label label-default">230</span>Messages</div>
                    <div class="content">
                        <ul>
                            <li>
                                <a href="#" class="clearfix">
                                    <figure class="image">
                                        <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Doe Junior" class="img-circle" />
                                    </figure>
                                    <span class="title">Joseph Doe</span>
                                    <span class="message">Lorem ipsum dolor sit.</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="clearfix">
                                    <figure class="image">
                                        <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Junior" class="img-circle" />
                                    </figure>
                                    <span class="title">Joseph Junior</span>
                                    <span class="message truncate">Truncated message. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet lacinia orci. Proin vestibulum eget risus non luctus. Nunc cursus lacinia lacinia. Nulla molestie malesuada est ac tincidunt. Quisque eget convallis diam, nec venenatis risus. Vestibulum blandit faucibus est et malesuada. Sed interdum cursus dui nec venenatis. Pellentesque non nisi lobortis, rutrum eros ut, convallis nisi. Sed tellus turpis, dignissim sit amet tristique quis, pretium id est. Sed aliquam diam diam, sit amet faucibus tellus ultricies eu. Aliquam lacinia nibh a metus bibendum, eu commodo eros commodo. Sed commodo molestie elit, a molestie lacus porttitor id. Donec facilisis varius sapien, ac fringilla velit porttitor et. Nam tincidunt gravida dui, sed pharetra odio pharetra nec. Duis consectetur venenatis pharetra. Vestibulum egestas nisi quis elementum elementum.</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="clearfix">
                                    <figure class="image">
                                        <img src="{% static 'images/!sample-user.jpg' %}" alt="Joe Junior" class="img-circle" />
                                    </figure>
                                    <span class="title">Joe Junior</span>
                                    <span class="message">Lorem ipsum dolor sit.</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="clearfix">
                                    <figure class="image">
                                        <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Junior" class="img-circle" />
                                    </figure>
                                    <span class="title">Joseph Junior</span>
                                    <span class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet lacinia orci. Proin vestibulum eget risus non luctus. Nunc cursus lacinia lacinia. Nulla molestie malesuada est ac tincidunt. Quisque eget convallis diam.</span>
                                </a>
                            </li>
                        </ul>
                        <hr />
                        <div class="text-right">
                            <a href="#" class="view-more">View All</a>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                    <i class="fa fa-bell"></i>
                    <span class="badge">3</span>
                </a>
                <div class="dropdown-menu notification-menu">
                    <div class="notification-title">
                        <span class="pull-right label label-default">3</span>
                        Alerts
                    </div>
                    <div class="content">
                        <ul>
                            <li>
                                <a href="#" class="clearfix">
                                    <div class="image">
                                        <i class="fa fa-thumbs-down bg-danger"></i>
                                    </div>
                                    <span class="title">Server is Down!</span>
                                    <span class="message">Just now</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="clearfix">
                                    <div class="image">
                                        <i class="fa fa-lock bg-warning"></i>
                                    </div>
                                    <span class="title">User Locked</span>
                                    <span class="message">15 minutes ago</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="clearfix">
                                    <div class="image">
                                        <i class="fa fa-signal bg-success"></i>
                                    </div>
                                    <span class="title">Connection Restaured</span>
                                    <span class="message">10/10/2014</span>
                                </a>
                            </li>
                        </ul>
                        <hr />
                        <div class="text-right">
                            <a href="#" class="view-more">View All</a>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
        <span class="separator"></span>
        
    </div>
</header>

scraping-estimation-tool/tool/templates/common/sidebar-right.html
{% load static %}
<aside id="sidebar-right" class="sidebar-right">
    <div class="nano">
        <div class="nano-content">
            <a href="#" class="mobile-close visible-xs"> Collapse <i class="fa fa-chevron-right"></i> </a>
            <div class="sidebar-right-wrapper">
                <div class="sidebar-widget widget-calendar">
                    <h6>Upcoming Tasks</h6>
                    <div data-plugin-datepicker data-plugin-skin="dark" ></div>
                    <ul>
                        <li>
                            <time datetime="2014-04-19T00:00+00:00">04/19/2014</time>
                            <span>Company Meeting</span>
                        </li>
                    </ul>
                </div>
                <div class="sidebar-widget widget-friends">
                    <h6>Friends</h6>
                    <ul>
                        <li class="status-online">
                            <figure class="profile-picture">
                                <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Doe" class="img-circle">
                            </figure>
                            <div class="profile-info">
                                <span class="name">Joseph Doe Junior</span>
                                <span class="title">Hey, how are you?</span>
                            </div>
                        </li>
                        <li class="status-online">
                            <figure class="profile-picture">
                                <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Doe" class="img-circle">
                            </figure>
                            <div class="profile-info">
                                <span class="name">Joseph Doe Junior</span>
                                <span class="title">Hey, how are you?</span>
                            </div>
                        </li>
                        <li class="status-offline">
                            <figure class="profile-picture">
                                <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Doe" class="img-circle">
                            </figure>
                            <div class="profile-info">
                                <span class="name">Joseph Doe Junior</span>
                                <span class="title">Hey, how are you?</span>
                            </div>
                        </li>
                        <li class="status-offline">
                            <figure class="profile-picture">
                                <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Doe" class="img-circle">
                            </figure>
                            <div class="profile-info">
                                <span class="name">Joseph Doe Junior</span>
                                <span class="title">Hey, how are you?</span>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</aside>

scraping-estimation-tool/tool/templates/common/sidebar.html
<!-- start: sidebar -->
<aside id="sidebar-left" class="sidebar-left">
    <div class="sidebar-header">
        <div class="sidebar-title">
            Navigation
        </div>
        <div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
            <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>
    <div class="nano">
        <div class="nano-content">
            <nav id="menu" class="nav-main" role="navigation">
                <ul class="nav nav-main">
                    <li><a href="{% url 'tool:index' %}"><i class="fa fa-home" aria-hidden="true"></i><span>Dashboard</span></a></li>
                    
                    <li><a href="{% url 'tool:entry' %}"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i><span>Website Entry</span></a></li>
                    <li><a href="{% url 'tool:input' %}"><i class="fa fa-edit" aria-hidden="true"></i><span>Xpath Input</span></a></li>
                    <li><a href="{% url 'tool:domain' %}"><i class="fa fa-file" aria-hidden="true"></i><span>Domain Info</span></a></li>
                </ul>
            </nav>
        </div>
    </div>
</aside>
<!-- end: sidebar -->

scraping-estimation-tool/tool/templates/domain.html
{% extends "base.html" %}
{% load static %}

{% block js%}
<script type="text/javascript" src="{% static 'js/domain.js' %}"></script>
{% endblock %}


{% block content %}
<section role="main" class="content-body">
    {% include "common/header-right.html" with title="Domains" parent_dir="Tables" child_dir="Basic" %}
    
    <div class="row">
        
        <div class="col-md-6">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <!-- <a href="#" class="fa fa-times"></a> -->
                    </div>

                    <h2 class="panel-title">Domain Information</h2>
                </header>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-hover mb-none">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Domain name</th>
                                    <th>Webscan report</th>
                                </tr>
                            </thead>
                            <tbody>
                                {%  for domain in domain_list %}
                                <tr>
                                    <td>{{forloop.counter0|add:1}}</td>
                                    <td>{{domain.domain}}</td>
                                    <td class="actions-hover actions-fade" onclick="openWebScanView('{{domain.domain}}');">
                                        {{domain.domain}}_report &nbsp;
                                        <a href="" ><i class="fa fa-file fa-lg" ></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
{% endblock %}

scraping-estimation-tool/tool/templates/entry.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<section role="main" class="content-body">
		{% include "common/header-right.html" with title="Website Entry" parent_dir="Analyze" child_dir="Dashboard" %}
		<form method="POST" action="/view_web/">
			{% csrf_token %}          
			<label for="fname">Link</label>
			<input type="text" id="link" name="link" placeholder="link of the page">

			<label for="lname">Domain</label>
			<input type="text" id="domain" name="domain" placeholder="example.com">
			
			 <input type="submit" value="Submit">
		</form>

</section>
{% endblock content %}

{% block js %}
	  <script src="{% static 'js/dashboard/twitter_daily.js' %}"></script>
{% endblock %}

scraping-estimation-tool/tool/templates/input.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<section role="main" class="content-body">
		{% include "common/header-right.html" with title="Xpath Input" parent_dir="Analyze" child_dir="Dashboard" %}
		<form method="POST">
			 <!-- action="/view_web/" -->
			{% csrf_token %}
		    {{ form }}		    
		    <!-- <label for="fname">Link</label>
			<input type="text" id="link" name="link" placeholder="link of the page">

			<label for="lname">Domain</label>
			<input type="text" id="domain" name="domain" placeholder="example.com">
			 -->
			 <input type="submit" value="Submit">
		</form>

</section>
{% endblock content %}

{% block js %}
	  <script src="{% static 'js/dashboard/twitter_daily.js' %}"></script>
{% endblock %}

scraping-estimation-tool/tool/templates/layouts/layouts-default.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section role="main" class="content-body">
    {% include "common/header-right.html" with title="Layouts" parent_dir="Layouts" child_dir="Default" %}
</section>
{% endblock content %}