kensetsubukka_server/accounts/urls.py
from django.contrib.auth.views import logout_then_login
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # Login
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', logout_then_login, name='logout'),
    # Signup
    path('signup/', views.Signup.as_view(), name='signup'),
    path('signup/done', views.SignupActivationConfirm.as_view(), name='signup_activation_confirm'),
    path('signup/complete/<token>', views.SignupActivationComplete.as_view(), name='signup_activation_complete'),
    # Password Reset
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    # Profile
    path('profile/', views.profile, name="profile")
]

kensetsubukka_server/dashboard/urls.py
from django.urls import include, path, re_path
from . import views
# from .subviews import youtube_views

app_name = 'dashboard'

urlpatterns = [
    #webage
    path('home/', views.index, name='index'),
    #js functions
    # path('start/', views.start, name='start'),
    path('download/', views.download, name='download'), # GET
    path('new_request/', views.request_scraping, name='new_request'), # POST
    path('cancel_request/', views.stop, name='cancel_request'), # POST
    path('update_status/', views.update_status, name='update_status'), # POST
    path('see_logs/', views.see_logs, name='see_logs'), # GET
    path('change_password/', views.change_password, name='change_password'), # POST
    path('update_database/', views.update_database, name='update_database') # POST
]

kensetsubukka_server/kensetsubukka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.i18n import JavaScriptCatalog
from dashboard import views
urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    # # url(r'^', include('dashboard.urls[0]')),
]
urlpatterns += [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

kensetsubukka_server/dashboard/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

class User_dashboard(models.Model):
    dashboard_id = models.AutoField(auto_created = True, primary_key = True, serialize = False)
    connected_user = models.ForeignKey(User, on_delete=models.CASCADE)

class Request(models.Model):
    task_id = models.AutoField(primary_key=True)
    unique_id = models.CharField(max_length=100, null=True, default=None)
    scrapy_task_id = models.CharField(max_length=100, null=True, default=None)
    connected_dashboard = models.ForeignKey(User_dashboard, on_delete=models.CASCADE)
    time_received = models.DateTimeField(default=datetime.now)
    time_start_scraping = models.DateTimeField(default=None, null=True)
    time_end_scraping = models.DateTimeField(default=None, null=True)
    time_end = models.DateTimeField(default=None, null=True)
    last_status = models.TextField(default="Request Received")
    Status = [
        (1, 'Submitted'),
        (2, 'Scraping'),
        (3, 'Error'),
        (4, 'Complete'),
        (5, 'Interrupted'),
        (6, 'Unknown'),
    ]
    running_status = models.IntegerField(default=0, choices=Status)
    filename = models.TextField(default=None, null=True, blank=True)
    was_downloaded = models.BooleanField(default=False)
    is_download_ready = models.BooleanField(default=False)
    is_show = models.BooleanField(default=True)






class Data(models.Model):
    unique_id = models.TextField(default=None, null=True, blank=True)
    count = models.TextField(default=None, null=True, blank=True)
    NETIS登録番号 = models.TextField(default=None, null=True, blank=True)
    技術名称 = models.TextField(default=None, null=True, blank=True)
    事後評価 = models.TextField(default=None, null=True, blank=True)
    受賞等_建設技術審査証明 = models.TextField(default=None, null=True, blank=True)
    受賞等_国土技術開発賞 = models.TextField(default=None, null=True, blank=True)
    受賞等_ものづくり日本大賞 = models.TextField(default=None, null=True, blank=True)
    受賞等_他機関の評価結果 = models.TextField(default=None, null=True, blank=True)
    事前審査_事後評価_試行実証評価 = models.TextField(default=None, null=True, blank=True)
    事前審査_事後評価_活用効果評価 = models.TextField(default=None, null=True, blank=True)
    事前審査_事後評価_事前審査 = models.TextField(default=None, null=True, blank=True)
    技術の位置付け_推奨技術 = models.TextField(default=None, null=True, blank=True)
    技術の位置付け_準推奨技術 = models.TextField(default=None, null=True, blank=True)
    技術の位置付け_評価促進技術 = models.TextField(default=None, null=True, blank=True)
    技術の位置付け_活用促進技術 = models.TextField(default=None, null=True, blank=True)
    level1 = models.TextField(default=None, null=True, blank=True)
    level2 = models.TextField(default=None, null=True, blank=True)
    level3 = models.TextField(default=None, null=True, blank=True)
    level4 = models.TextField(default=None, null=True, blank=True)
    技術会社 = models.TextField(default=None, null=True, blank=True)
    技術_担当部署 = models.TextField(default=None, null=True, blank=True)
    技術_担当者 = models.TextField(default=None, null=True, blank=True)
    技術部署_住所 = models.TextField(default=None, null=True, blank=True)
    技術部署_Tel = models.TextField(default=None, null=True, blank=True)
    技術部署_FAX = models.TextField(default=None, null=True, blank=True)
    技術部署_Email = models.TextField(default=None, null=True, blank=True)
    技術部署_URL = models.TextField(default=None, null=True, blank=True)
    営業会社 = models.TextField(default=None, null=True, blank=True)
    営業_担当部署 = models.TextField(default=None, null=True, blank=True)
    営業部署_担当者 = models.TextField(default=None, null=True, blank=True)
    営業部署_住所 = models.TextField(default=None, null=True, blank=True)
    営業部署_Tel = models.TextField(default=None, null=True, blank=True)
    営業部署_FAX = models.TextField(default=None, null=True, blank=True)
    営業部署_Email = models.TextField(default=None, null=True, blank=True)
    営業部署_URL = models.TextField(default=None, null=True, blank=True)

kensetsubukka_server/dashboard/views.py
from datetime import datetime

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .models import Request, User_dashboard
from .subviews.home_subviews import change_request_status, create_new_request, cancel_request, download_files, do_operation

""" ----------------------------------------------------------------------------------------------------------------------------------------"""
""" Main functions of backend STARTS here"""

@login_required
@csrf_exempt
def index(request):
    context = do_operation(request,action="")
    return render(request, 'index.html', context)



@login_required
@csrf_exempt
def request_scraping(request):
    context = do_operation(request,action="start")
    template = render_to_string('table.html',context,request=request)
    return JsonResponse(template, safe=False)


@login_required
@csrf_exempt
def stop(request):
    context = do_operation(request,action="stop")
    template = render_to_string('table.html',context,request=request)
    return JsonResponse(template, safe=False)


@login_required
@csrf_exempt
def download(request):
    user = request.user
    dashboard = User_dashboard.objects.get(connected_user=user)
    task_id = request.GET['task_id']
    task_id = int(task_id)
    task = Request.objects.get(task_id=task_id)
    if(task.connected_dashboard == dashboard):
        task_id = int(task_id)
        response = download_files(task_id)
        return response
    else:
        return HttpResponse(gettext_lazy("Task ID doesn't belong to this User"))



@login_required
@csrf_exempt
def update_status(request):
    requests = Request.objects.filter(running_status__in=[3,5,6])
    for req in requests:
        req.is_show=False
        req.save()
    requests = Request.objects.filter(running_status=5)
    return JsonResponse({"message":gettext_lazy("Successfully removed request from database.")})



@login_required
@csrf_exempt
def see_logs(request):
    user = request.user
    dashboard = User_dashboard.objects.get(connected_user=user)
    requests_set = list(Request.objects.filter(connected_dashboard=dashboard).order_by('-task_id'))
    requests = requests_set
    context = {"requests":requests}
    template = render_to_string('logs.html',context,request=request)
    return JsonResponse(template, safe=False)



@login_required
@csrf_exempt
def change_password(request):
    if request.method == 'POST':
        # print(request.POST)
        form = PasswordChangeForm(request.user, request.POST)
        # print(form)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            message = gettext_lazy("Password Changed Successfully.")
            # messages.success(request, 'Your password was successfully updated!')
            # context={"message":"Password changed successfully"}
        else:
            message = gettext_lazy("Incorrect Entries")
            # messages.error(request, 'Please correct the error below.')
            
    else:
        form = PasswordChangeForm(request.user)
        message = ""
    
    context={"form":form,"message":message}

    template = render_to_string('password_form.html',context,request=request)
    return JsonResponse(template, safe=False)


""" Main fucntion of backend ENDS here """
""" ----------------------------------------------------------------------------------------------------------------------------------------"""
""" Function for API access of backend STARTS here"""


@api_view(['GET', 'POST'])
@csrf_exempt
def update_database(request):
    if request.method == 'POST':
        try :
            print(request.data)
            task_id = request.data['task_id']
            status = request.data['status']
            print(task_id,status)
            task_id = int(task_id)
            status = int(status)
            request = Request.objects.get(task_id=task_id)
            change_request_status(request,status,datetime.now())
        except :
            print ("error occured")
            return Response({"message": "Data format incorrect."})
        return Response({"message": "requested data updated successfully"})
    return Response({"message": "API successfully accessed"})


""" Function for API access of backend ENDS here. """
""" ----------------------------------------------------------------------------------------------------------------------------------------"""

kensetsubukka_server/dashboard/templates/common/error.html
{% load static %}
<div class="row">
    <div class="col-md-8">
        <div class="main-error mb-xlg">
            <h2 class="error-code text-dark text-center text-semibold m-none">{{ title }} <i class="fa fa-file"></i></h2>
            <p class="error-explanation text-center">{{ message }}</p>
        </div>
    </div>
    <div class="col-md-4">
        <h4 class="text">Here are some useful links</h4>
        <ul class="nav nav-list primary">
            <li><a href="#"><i class="fa fa-caret-right text-dark"></i> Dashboard</a></li>
            <li><a href="#"><i class="fa fa-caret-right text-dark"></i> User Profile</a></li>
            <li><a href="#"><i class="fa fa-caret-right text-dark"></i> FAQ's</a></li>
        </ul>
    </div>
</div>

kensetsubukka_server/dashboard/templates/common/footer.html
{% load static %}
<p class="text-center text-muted mt-md mb-md">
    &copy; Indigo Data <a href="{{ COMPANY_URL }}" target="_blank">{{ COMPANY_NAME }}</a>.
</p>

kensetsubukka_server/dashboard/templates/common/header-right.html
{% load static %}
<header class="page-header">
    <h2>{{ title }}</h2>
    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li><span>{{ parent_dir }}</span></li>
            <li><span>{{ child_dir }}</span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

kensetsubukka_server/dashboard/templates/common/header.html
{% load static %}
{% load i18n %}
<header class="header">
    <div class="logo-container">
        <a href="../" class="logo"><img src="{% static 'images/logo.png' %}" height="35" alt="Logo" /></a>
        <div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
            <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>
    <!-- start: search & user box -->
    <div class="header-right">
        <form action="../pages/pages-search-results.html" class="search nav-form" style="margin-bottom: 0;">
            <div class="input-group input-search">
                <input type="text" class="form-control" name="q" id="q" placeholder="Search...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <span class="separator"></span>
        <ul class="notifications">
            <li>
                <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                    <i class="fa fa-tasks"></i>
                    <span class="badge">3</span>
                </a>
                <div class="dropdown-menu notification-menu large">
                    <div class="notification-title">
                        <span class="pull-right label label-default">3</span>Tasks
                    </div>
                    <div class="content">
                        <ul>
                            <li>
                                <p class="clearfix mb-xs">
                                <span class="message pull-left">Generating Sales Report</span>
                                <span class="message pull-right text-dark">60%</span>
                                </p>
                                <div class="progress progress-xs light">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
                                </div>
                            </li>
                            <li>
                                <p class="clearfix mb-xs">
                                <span class="message pull-left">Importing Contacts</span>
                                <span class="message pull-right text-dark">98%</span>
                                </p>
                                <div class="progress progress-xs light">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100" style="width: 98%;"></div>
                                </div>
                            </li>
                            <li>
                                <p class="clearfix mb-xs">
                                <span class="message pull-left">Uploading something big</span>
                                <span class="message pull-right text-dark">33%</span>
                                </p>
                                <div class="progress progress-xs light mb-xs">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%;"></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
            <li>
                <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                    <i class="fa fa-envelope"></i>
                    <span class="badge">4</span>
                </a>
                <div class="dropdown-menu notification-menu">
                    <div class="notification-title">
                        <span class="pull-right label label-default">230</span>Messages</div>
                    <div class="content">
                        <ul>
                            <li>
                                <a href="#" class="clearfix">
                                    <figure class="image">
                                        <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Doe Junior" class="img-circle" />
                                    </figure>
                                    <span class="title">Joseph Doe</span>
                                    <span class="message">Lorem ipsum dolor sit.</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="clearfix">
                                    <figure class="image">
                                        <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Junior" class="img-circle" />
                                    </figure>
                                    <span class="title">Joseph Junior</span>
                                    <span class="message truncate">Truncated message. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet lacinia orci. Proin vestibulum eget risus non luctus. Nunc cursus lacinia lacinia. Nulla molestie malesuada est ac tincidunt. Quisque eget convallis diam, nec venenatis risus. Vestibulum blandit faucibus est et malesuada. Sed interdum cursus dui nec venenatis. Pellentesque non nisi lobortis, rutrum eros ut, convallis nisi. Sed tellus turpis, dignissim sit amet tristique quis, pretium id est. Sed aliquam diam diam, sit amet faucibus tellus ultricies eu. Aliquam lacinia nibh a metus bibendum, eu commodo eros commodo. Sed commodo molestie elit, a molestie lacus porttitor id. Donec facilisis varius sapien, ac fringilla velit porttitor et. Nam tincidunt gravida dui, sed pharetra odio pharetra nec. Duis consectetur venenatis pharetra. Vestibulum egestas nisi quis elementum elementum.</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="clearfix">
                                    <figure class="image">
                                        <img src="{% static 'images/!sample-user.jpg' %}" alt="Joe Junior" class="img-circle" />
                                    </figure>
                                    <span class="title">Joe Junior</span>
                                    <span class="message">Lorem ipsum dolor sit.</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="clearfix">
                                    <figure class="image">
                                        <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Junior" class="img-circle" />
                                    </figure>
                                    <span class="title">Joseph Junior</span>
                                    <span class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet lacinia orci. Proin vestibulum eget risus non luctus. Nunc cursus lacinia lacinia. Nulla molestie malesuada est ac tincidunt. Quisque eget convallis diam.</span>
                                </a>
                            </li>
                        </ul>
                        <hr />
                        <div class="text-right">
                            <a href="#" class="view-more">View All</a>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                    <i class="fa fa-bell"></i>
                    <span class="badge">3</span>
                </a>
                <div class="dropdown-menu notification-menu">
                    <div class="notification-title">
                        <span class="pull-right label label-default">3</span>
                        Alerts
                    </div>
                    <div class="content">
                        <ul>
                            <li>
                                <a href="#" class="clearfix">
                                    <div class="image">
                                        <i class="fa fa-thumbs-down bg-danger"></i>
                                    </div>
                                    <span class="title">Server is Down!</span>
                                    <span class="message">Just now</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="clearfix">
                                    <div class="image">
                                        <i class="fa fa-lock bg-warning"></i>
                                    </div>
                                    <span class="title">User Locked</span>
                                    <span class="message">15 minutes ago</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="clearfix">
                                    <div class="image">
                                        <i class="fa fa-signal bg-success"></i>
                                    </div>
                                    <span class="title">Connection Restaured</span>
                                    <span class="message">10/10/2014</span>
                                </a>
                            </li>
                        </ul>
                        <hr />
                        <div class="text-right">
                            <a href="#" class="view-more">View All</a>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
        <span class="separator"></span>
        <div id="userbox" class="userbox">
            <a href="#" data-toggle="dropdown">
                <figure class="profile-picture">
                    <img src="{% static 'images/!logged-user.png' %}" alt="Joseph Doe" class="img-circle" data-lock-picture="{% static 'images/!logged-user.jpg' %}" />
                </figure>
                <div class="profile-info" data-lock-name="John Doe" data-lock-email="johndoe@JSOFT.com">
                    <span class="name">{{ user.email }}</span>
                    <span class="role">administrator</span>
                </div>
                <i class="fa custom-caret"></i>
            </a>
            <div class="dropdown-menu">
                <ul class="list-unstyled">
                    <li class="divider"></li>
                    <li>
                        <a role="menuitem" tabindex="-1" href="{%  url "accounts:profile" %}"><i class="fa fa-user"></i> My Profile</a>
                    </li>
                    <li>
                        <a role="menuitem" tabindex="-1" href="#" data-lock-screen="true"><i class="fa fa-lock"></i> Lock Screen</a>
                    </li>
                    <li>
                        <a role="menuitem" tabindex="-1" href="{% url "accounts:logout" %}"><i class="fa fa-power-off"></i> {% trans "Logout" %}</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>

kensetsubukka_server/dashboard/templates/common/header_1.html
{% load i18n %}
{% load static %}
<header class="header">
    <div class="logo-container">
        <a href="{% url "dashboard:index" %}" class="logo"><img src="{% static 'images/bukka_logo.png' %}" height="35" alt="Logo" /></a>
    </div>
    
    <div class="header-right">
        <span class="separator"></span>
        <span class="separator"></span>
        {% if user.is_authenticated %}
        <ul class="notifications">
           <li>
            <a href="{% url "accounts:logout" %}">
                <i class="fa fa-sign-in fa-lg"></i>&nbsp; {% trans "Logout" %}
            </a>
           </li> 
        </ul>
        <span class="separator"></span>
        {% else %}
        <ul class="notifications">
           <li>
            <a href="{% url "accounts:login" %}">
                <i class="fa fa-sign-in fa-lg"></i>&nbsp; {% trans "Login" %}
            </a>
           </li> 
        </ul>
        <span class="separator"></span>
        <ul class="notifications">
            <li>
             <a href="{% url "accounts:signup" %}">
                 <i class="fa fa-user fa-lg"></i>&nbsp; {% trans "Signup" %}
             </a>
            </li> 
         </ul>
         <span class="separator"></span>
        {% endif %}
        <ul class="notifications">
           <li>
            
           </li> 
        </ul>
        
    </div>
</header>

kensetsubukka_server/dashboard/templates/common/sidebar-right.html
{% load static %}
<aside id="sidebar-right" class="sidebar-right">
    <div class="nano">
        <div class="nano-content">
            <a href="#" class="mobile-close visible-xs"> Collapse <i class="fa fa-chevron-right"></i> </a>
            <div class="sidebar-right-wrapper">
                <div class="sidebar-widget widget-calendar">
                    <h6>Upcoming Tasks</h6>
                    <div data-plugin-datepicker data-plugin-skin="dark" ></div>
                    <ul>
                        <li>
                            <time datetime="2014-04-19T00:00+00:00">04/19/2014</time>
                            <span>Company Meeting</span>
                        </li>
                    </ul>
                </div>
                <div class="sidebar-widget widget-friends">
                    <h6>Friends</h6>
                    <ul>
                        <li class="status-online">
                            <figure class="profile-picture">
                                <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Doe" class="img-circle">
                            </figure>
                            <div class="profile-info">
                                <span class="name">Joseph Doe Junior</span>
                                <span class="title">Hey, how are you?</span>
                            </div>
                        </li>
                        <li class="status-online">
                            <figure class="profile-picture">
                                <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Doe" class="img-circle">
                            </figure>
                            <div class="profile-info">
                                <span class="name">Joseph Doe Junior</span>
                                <span class="title">Hey, how are you?</span>
                            </div>
                        </li>
                        <li class="status-offline">
                            <figure class="profile-picture">
                                <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Doe" class="img-circle">
                            </figure>
                            <div class="profile-info">
                                <span class="name">Joseph Doe Junior</span>
                                <span class="title">Hey, how are you?</span>
                            </div>
                        </li>
                        <li class="status-offline">
                            <figure class="profile-picture">
                                <img src="{% static 'images/!sample-user.jpg' %}" alt="Joseph Doe" class="img-circle">
                            </figure>
                            <div class="profile-info">
                                <span class="name">Joseph Doe Junior</span>
                                <span class="title">Hey, how are you?</span>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</aside>

kensetsubukka_server/dashboard/templates/common/sidebar.html
{% load i18n %}
<!-- start: sidebar -->
<aside id="sidebar-left" class="sidebar-left" style="opacity: 0.9;color:white;font-weight: 600;">
    <div class="sidebar-header" style="background-color: black;">
        <div class="sidebar-title">
            {% trans "Welcome" %} , {{user.username}}
        </div>
        <div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
            <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>
    <div class="nano-different">
        <div class="nano-content">
            <nav id="menu" class="nav-main" role="navigation">
                <ul class="nav nav-main">
                    <li><a onclick="see_logs()" data-toggle="tooltip" data-placement="right"><i class="fa fa-clock-o" aria-hidden="true"></i><span> {% trans "Logs & History" %}</span></a></li>
                    <li><a onclick="change_password()" data-toggle="tooltip" data-placement="right"><i class="fa fa-cogs" aria-hidden="true"></i><span>{% trans "Change Password" %}</span></a></li>
                    <!-- <li><a onclick="on()" data-toggle="tooltip" data-placement="right" title="{% trans "Change notification mail" %}"><i class="fa fa-user" aria-hidden="true"></i><span>{% trans "Change Email Address" %} (Not Done yet)</span></a></li> -->
                </ul>
            </nav>
        </div>
    </div>
</aside>
<!-- end: sidebar -->

kensetsubukka_server/dashboard/templates/common/sidebar_1.html
<!-- SideNav slide-out button -->
<!--/. Sidebar navigation -->